version: '2'
services:
    referable-app:
        image: referable
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://referable-postgresql:5432/referable
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=referable-elasticsearch:9300
        ports:
            - 8080:8080
    referable-postgresql:
        extends:
            file: postgresql.yml
            service: referable-postgresql
    referable-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: referable-elasticsearch
